version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      time: "04:00"
      interval: "monthly"
      timezone: Asia/Shanghai
    ignore:
      - dependency-name: semantic-release
      - dependency-name: "sass"
        versions:
          - ">= 2.0.0"
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: Asia/Shanghai
