version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      time: "04:00"
      interval: daily
      timezone: Asia/Shanghai
    ignore:
      - dependency-name: semantic-release
      - dependency-name: "@commitlint/config-conventional"
        versions:
          - ">= 19.0.0"
      - dependency-name: "sass"
        versions:
          - ">= 2.0.0"
