version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
      timezone: Asia/Shanghai
    ignore:
      - dependency-name: semantic-release
