name: Feature Request
description: 新功能请求
title: "[feature]: "
labels: ["enhancement"]
# assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**

        您的功能请求是否与问题有关？请描述。

  - type: input
    id: problem-description
    attributes:
      label: Problem Description
      description: 请提供对问题的清晰简洁的描述。例如，当 [...]
      placeholder: 例如，当我尝试 [...] 时，我总是感到沮丧。
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like/描述您想要的解决方案**

        对你想要发生的事情进行清晰简洁的描述。

  - type: input
    id: solution-description
    attributes:
      label: Solution Description
      description: 请描述您想要的解决方案。
      placeholder: 例如，我希望有一个功能可以 [...]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Describe alternatives you've considered/描述您考虑过的备选方案**

        对您考虑过的任何替代解决方案或功能的清晰简洁的描述。

  - type: input
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: 请描述您考虑过的任何替代解决方案或功能。
      placeholder: 例如，我考虑过使用 [...] 作为替代方案。
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Additional context/附加上下文**

        在此处添加有关功能请求的任何其他上下文或屏幕截图。

  - type: input
    id: additional-context
    attributes:
      label: Additional Context
      description: 请提供任何其他相关的上下文信息或屏幕截图链接。
      placeholder: 例如，https://example.com/screenshot.png
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Paid Consultation/付费咨询**

        如果您愿意支付费用以获得更快的功能开发优先级，请[前往爱发电进行赞助](https://afdian.com/a/CaoMeiYouRen)。

        如果您不愿意付费，请耐心等待开发者回复。开发者可能因为各种各样的原因无法及时回复，还请谅解。
