name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Add Issue to Project
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: "RSS Impact 项目"
          column: "Todo"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "add"
