name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    permissions:
      issues: write
      repository-projects: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: skeet70/default-project-board-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 1
